name: playground CI

#on:
#  push:
#    branches:
#      - main

on: workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Check migrations
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}
          ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
        run: |
          cd backend
          python manage.py makemigrations --check --dry-run
          
      - name: Run tests
        env: 
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ vars.DEBUG }}
          ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
        run: |
          cd backend
          python manage.py test
